BACKEND_URL = ""

GOOGLE_AUTH_URL = ""
AUTH_REFRESH_URL = ""
AUTH_ME_URL = ""

DOMAIN_PREFIX = ""

RESOURCES_URL = ""
ACCOUNTS_URL = ""
TRANSACTIONS_URL = ""
PLANNED_URL = ""

__all__ = [
    "BACKEND_URL",
    "GOOGLE_AUTH_URL",
    "AUTH_REFRESH_URL",
    "AUTH_ME_URL",
    "DOMAIN_PREFIX",
    "RESOURCES_URL",
    "ACCOUNTS_URL",
    "TRANSACTIONS_URL",
    "PLANNED_URL",
]
